### ISSUE TITLE
Mod Compatibility with Actually Additions AIOT Tool

### ISSUE THREAD

**Issue by WenXin20** [TheXFactor117/Levels#28]
The AIOT Tool doesn't get any levels even though it is a weapon.

**Comment by TheXFactor117** [comment]
There's nothing I can do about it due to the way all-in-one-tools work. There is a very slight chance that I can manually add compatibility for it, but I'll have to think about that in the future.

Unfortunately I wished it would work properly, but the way that item is handled causes Levels not to work.

**Comment by WenXin20** [comment]
Ok, thanks anyway
