### ISSUE TITLE
Percentage of Drop Quality STILL not working.

### ISSUE THREAD

**Issue by Boolyman** [TheXFactor117/Levels#94]
Over a month ago I reported that the Percentage of drops for the different qualities in the configuration was not working.  Even after reducing the percentage for certain qualities to 0%... they continued to drop.  It was in conjunction with my report that the MMMM dummies were levelling up weapons.  Well... neither one of those issues have been fixxed for 1.10.... the ticket has been made blank, but is still sitting there.  And you guys only seem to care about 1.11 updates.  

With all due respect, would you recommend I try working with a different mod, or do you guys plan on fixxing the issues with 1.10?  All of the big name mod teams are sitting at 1.10 for their packs... so im not sure why 1.11 is such a big focus... but thats none of my business.  I just need to know if you are going to be maintaining 1.10 regularly, or if we should commission a different mod to be used.

**Comment by TheXFactor117** [comment]
The issue is fixed - for 1.11.2 at least - but I understand you aren't using that specific version. I will look into back porting the most recent version back to 1.10.2 right now.

However, I will say something in regards to mods and developing for different versions. Typically, maintaining two Minecraft's makes things on the developers end a pain in the ass. Essentially, I make all the changes I want in the "main" version, and porting them to the "other" version essentially means re-writing either the new changes or re-writing ALL of the issues between the two Minecraft versions. It's always one way or the other. I myself have a lot of different projects I'm working on, and I really don't want to support multiple Minecraft versions actively. However, I realize a lot of people aren't using 1.11.2, so I'll try and give some more support to 1.10.2.

**Comment by TheXFactor117** [comment]
I just finished back porting r1.2.1 to 1.10.2. It should be up in a couple minutes on CurseForge.
